apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mscchronos
  name: mscchronos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mscchronos
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - image: "juansorduz/clearwater-mscchronos:latest"
        imagePullPolicy: Always
        name: mscchronos
        ports:
        - containerPort: 22
        - containerPort: 7253
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7253"]
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7253"]
        volumeMounts:
        - name: chronoslogs
          mountPath: /var/log/chronos
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "/usr/bin/pre-stop"]
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/chronos/chronos_current.txt" ]
        volumeMounts:
        - name: chronoslogs
          mountPath: /var/log/chronos
      volumes:
      - name: chronoslogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
