apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msccassandra
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: msccassandra
    spec:
      containers:
      - image: "juansorduz/clearwater-msccassandra:latest"
        imagePullPolicy: Always
        name: msccassandra
        ports:
        - containerPort: 22
        - containerPort: 7001
        - containerPort: 9042
        - containerPort: 9160
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7000 9042 9160"]
          # Cassandra can take a very, very long time to start up
          initialDelaySeconds: 600
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "7000 9042 9160"]
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
      nodeSelector:
        Tnode: notsipp
