apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mscsprout
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mscsprout
  template:
    metadata:
      labels:
        service: mscsprout
        snmp: enabled
    spec:
      containers:
      - image: "juansorduz/clearwater-mscsprout:latest"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
        name: mscsprout
        ports:
        - containerPort: 22
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5052"]
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "5054"]
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      - image: busybox
        resources:
          requests:
            cpu: "0.1"
        name: tailer
        command: [ "tail", "-F", "/var/log/sprout/sprout_current.txt" ]
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      volumes:
      - name: sproutlogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
      nodeSelector:
        Tnode: notsipp
