apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: cassandra
    spec:
      containers:
      - image: "gabrielorozco20/clearwater-cassandra:latest"
        imagePullPolicy: Always
        name: cassandra
        ports:
        - containerPort: 22
        - containerPort: 7001
        - containerPort: 9042
        - containerPort: 9160
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
