apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homestead-prov
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homestead-prov
  template:
    metadata:
      labels:
        service: homestead-prov
        snmp: enabled
    spec:
      containers:
      - image: "gabrielorozco20/clearwater-homestead-prov:lastest"
        imagePullPolicy: Always
        name: homestead-prov
        ports:
        - containerPort: 22
        - containerPort: 8889
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
