apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homestead
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homestead
  template:
    metadata:
      labels:
        service: homestead
        snmp: enabled
    spec:
      containers:
      - image: "juansorduz/clearwater-homestead:latest"
        imagePullPolicy: Always
        name: homestead
        ports:
        - containerPort: 22
        - containerPort: 8888
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/homestead/homestead_current.txt" ]
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      volumes:
      - name: homesteadlogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
