apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sprout
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sprout
  template:
    metadata:
      labels:
        service: sprout
        snmp: enabled
    spec:
      containers:
      - image: "gabrielorozco20/clearwater-sprout:lastest"
        imagePullPolicy: Always
        name: sprout
        ports:
        - containerPort: 22
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/sprout/sprout_current.txt" ]
        volumeMounts:
        - name: sproutlogs
          mountPath: /var/log/sprout
      volumes:
      - name: sproutlogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
